name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3.'
inputs:
  bucket:
    description: 'Name of the S3 bucket to deploy to.'
    required: true
  region:
    description: 'AWS region where the S3 bucket is located.'
    required: false
    default: 'ap-southeast-1'
  dist-folder:
    description: 'Folder containing the static files to deploy.'
    required: true
    default: 'dist'
outputs:
  website-url:
    description: 'URL of the deployed static website.'
runs:
  using: 'node16'
  main: 'main.js'